configuration :
  - name : alice
    ip : 127.0.0.1
    port : 12344
  - name : bob
    ip : 127.0.0.1
    port : 14255
  - name : charlie
    ip : 127.0.0.1
    port : 12998
  - name : deadpool
    ip : 127.0.0.1
    port : 1987

groups :
  - name : Group1
    members :
      - alice
      - bob
      - charlie
  - name : Group2
    members :
      - deadpool

sendRules :
  - action : delay
    src : alice
    kind : delay

  - action : drop
    src : alice
    dest : charlie
    kind : drop

receiveRules :
  - action : drop
    src : alice
    dest : bob
    kind : drop2

