configuration :
  - name : alice
    ip : 127.0.0.1
    port : 12344
  - name : bob
    ip : 127.0.0.1
    port : 14255
  - name : charlie
    ip : 127.0.0.1
    port : 12998
  - name : deadpool
    ip : 127.0.0.1
    port : 1987
  - name : logger
    ip : 127.0.0.1
    port : 2006
 
sendRules :
  - action : drop
    src : bob
    dest : charlie

  - action : delay
    src : bob
    dest : deadpool

receiveRules :
  - action : delay
    src : bob
    dest : deadpool

  - action : drop
    src : charlie
    dest : deadpool
