configuration :
  - name : alice
    ip : 127.0.0.1
    port : 12345
    memberOf : Group1
  - name : bob
    ip : 127.0.0.1
    port : 14255
    memberOf : Group2
  - name : charlie
    ip : 127.0.0.1
    port : 12998
    memberOf : Group3
  - name : david
    ip : 127.0.0.1
    port : 19873
    memberOf : Group4
  - name : eve
    ip : 127.0.0.1
    port : 19872
    memberOf : Group5
  - name : frank
    ip : 127.0.0.1
    port : 14456
    memberOf : Group6
  - name : green
    ip : 127.0.0.1
    port : 19876
    memberOf : Group7


groups :
  - name : Group1
    members :
      - alice
      - bob
      - charlie
  - name : Group2
    members :
      - bob
      - david
      - frank
  - name : Group3
    members :
      - charlie
      - eve
      - frank
  - name : Group4
    members :
      - alice
      - david
      - eve
  - name : Group5
    members :
      - bob
      - eve
      - green
  - name : Group6
    members :
      - alice
      - frank
      - green
  - name : Group7
    members :
      - charlie
      - david
      - green
